export const projects = [
  {
    id: 1,
    title: "Flight Delay Analytics Pipeline",
    description: "Real-time + batch ELT pipeline on GCP. Pub/Sub → Dataflow → GCS → PySpark → BigQuery → Looker Studio.",
    tech: ["Pub/Sub", "Dataflow", "PySpark", "BigQuery", "Airflow", "GCP"],
    image: "/images/Flight_pipeline.png",
    github: "https://github.com/mohammedjunaidkhan980/Flight_Pipeline",
    live: "https://github.com/mohammedjunaidkhan980/Flight_Pipeline",
    color: "#2F73FF",
  },
  {
    id: 2,
    title: "GCP DBT Finance Pipeline",
    description: "End-to-end ELT pipeline with dbt + BigQuery. Finance transactions through staging, intermediate and marts layers.",
    tech: ["dbt", "BigQuery", "GCS", "Python", "Looker Studio"],
    image: "/images/dbt_Bg.png",
    github: "https://github.com/mohammedjunaidkhan980/GCP_DBT_Project",
    live: "https://github.com/mohammedjunaidkhan980/GCP_DBT_Project",
    color: "#F2388F",
  },
  {
    id: 3,
    title: "Multi-Agent Career Platform",
    description: "4 specialized AI agents — Skill Gap Advisor, Mock Interviewer, Salary Advisor — with LLM-powered master router.",
    tech: ["Java", "Spring Boot", "LangChain4j", "Azure OpenAI", "React"],
    image: "/images/MULTI_AGENT.png",
    github: "https://github.com/mohammedjunaidkhan980/MULTI_AGENT",
    live: "https://github.com/mohammedjunaidkhan980/MULTI_AGENT",
    color: "#76E36A",
  },
  {
    id: 4,
    title: "RAG HR Assistant",
    description: "AI-powered HR document Q&A system. PDF chunking, vector embeddings, cosine similarity search, Azure OpenAI.",
    tech: ["Java", "Spring Boot", "LangChain4j", "Azure OpenAI", "PostgreSQL"],
    image: "/images/hr_rag.png",
    github: "https://github.com/mohammedjunaidkhan980/RAG_hr_system",
    live: "https://github.com/mohammedjunaidkhan980/RAG_hr_system",
    color: "#EFCF35",
  },
  {
    id: 5,
    title: "SpringSweets Microservices",
    description: "Full microservices e-commerce platform with 8 services, Stripe payments, Cloudinary uploads, Redis caching.",
    tech: ["Java", "Spring Boot", "Spring Cloud", "Redis", "Kafka", "React"],
    image: "/images/SpringSweets.png",
    github: "https://github.com/mohammedjunaidkhan980/SpringSweets",
    live: "https://github.com/mohammedjunaidkhan980/SpringSweets",
    color: "#F2388F",
  },
];

export const skills = [
  { name: "Java", color: "#F2388F" },
  { name: "Spring Boot", color: "#76E36A" },
  { name: "Spring Cloud", color: "#76E36A" },
  { name: "Kafka", color: "#111111" },
  { name: "React", color: "#2F73FF" },
  { name: "Python", color: "#EFCF35" },
  { name: "GCP", color: "#2F73FF" },
  { name: "BigQuery", color: "#2F73FF" },
  { name: "dbt", color: "#F2388F" },
  { name: "PySpark", color: "#F2388F" },
  { name: "Airflow", color: "#76E36A" },
  { name: "Dataflow", color: "#2F73FF" },
  { name: "Pub/Sub", color: "#76E36A" },
  { name: "LangChain4j", color: "#111111" },
  { name: "Redis", color: "#F2388F" },
  { name: "PostgreSQL", color: "#2F73FF" },
  { name: "MongoDB", color: "#76E36A" },
  { name: "Docker", color: "#2F73FF" },
];

export const timeline = [
  {
    year: "Jul 2025 – Jul 2026",
    title: "Software Engineer @ Capgemini",
    description: "Joined as Java Full Stack Engineer. Built production microservices with Spring Boot and Spring Cloud.",
    color: "#2F73FF",
  },
  {
    year: "Late 2025",
    title: "Generative AI Engineering",
    description: "Built RAG HR Assistant and Multi-Agent Career Platform using LangChain4j and Azure OpenAI.",
    color: "#F2388F",
  },
  {
    year: "Early 2026",
    title: "Google Cloud Associate Engineer",
    description: "Earned Google Cloud Associate Cloud Engineer certification through Google Partner program.",
    color: "#76E36A",
  },
  {
    year: "Jul 2026 – Present",
    title: "GCP Data Engineering",
    description: "Transitioning into GCP Data Engineering. Building real-time pipelines with Pub/Sub, Dataflow, PySpark, dbt and Airflow.",
    color: "#EFCF35",
  },
];
