export const projectSections = [
  {
    id: 1,
    section: "Java & AI",
    subtitle: "// JAVA + GENERATIVE AI",
    color: "#76E36A",
    projects: [
      {
        id: 5,
        title: "SpringSweets Microservices",
        description: "Full microservices e-commerce platform with 8 services, Stripe payments, Cloudinary uploads, Redis caching.",
        tech: ["Java", "Spring Boot", "Spring Cloud", "Redis", "Kafka", "React"],
        image: "/images/SpringSweets.png",
        github: "https://github.com/mohammedjunaidkhan980/SpringSweets",
        live: "https://github.com/mohammedjunaidkhan980/SpringSweets",
        color: "#F2388F",
      },
      {
        id: 3,
        title: "Multi-Agent Career Platform",
        description: "4 specialized AI agents — Skill Gap Advisor, Mock Interviewer, Salary Advisor — with LLM-powered master router.",
        tech: ["Java", "Spring Boot", "LangChain4j", "Azure OpenAI", "React"],
        image: "/images/MULTI_AGENT.png",
        github: "https://github.com/mohammedjunaidkhan980/MULTI_AGENT",
        live: "https://github.com/mohammedjunaidkhan980/MULTI_AGENT",
        color: "#76E36A",
      },
    ],
  },
  {
    id: 2,
    section: "Python & AI",
    subtitle: "// PYTHON + GENERATIVE AI",
    color: "#F2388F",
    projects: [
      {
        id: 4,
        title: "RAG HR Assistant",
        description: "AI-powered HR document Q&A system. PDF chunking, vector embeddings, cosine similarity search, Azure OpenAI.",
        tech: ["Python", "LangChain4j", "Azure OpenAI", "PostgreSQL", "FastAPI"],
        image: "/images/hr_rag.png",
        github: "https://github.com/mohammedjunaidkhan980/RAG_hr_system",
        live: "https://github.com/mohammedjunaidkhan980/RAG_hr_system",
        color: "#EFCF35",
      },
      {
        id: 3,
        title: "Multi-Agent Career Platform",
        description: "4 specialized AI agents — Skill Gap Advisor, Mock Interviewer, Salary Advisor — with LLM-powered master router.",
        tech: ["Python", "LangChain4j", "Azure OpenAI", "FastAPI", "React"],
        image: "/images/MULTI_AGENT.png",
        github: "https://github.com/mohammedjunaidkhan980/MULTI_AGENT",
        live: "https://github.com/mohammedjunaidkhan980/MULTI_AGENT",
        color: "#76E36A",
      },
    ],
  },
  {
    id: 3,
    section: "GCP DE & Python",
    subtitle: "// GCP DATA ENGINEERING + PYTHON",
    color: "#2F73FF",
    projects: [
      {
        id: 2,
        title: "GCP DBT Finance Pipeline",
        description: "End-to-end ELT pipeline with dbt + BigQuery. Finance transactions through staging, intermediate and marts layers.",
        tech: ["dbt", "BigQuery", "GCS", "Python", "Looker Studio"],
        image: "/images/dbt_Bg.png",
        github: "https://github.com/mohammedjunaidkhan980/GCP_DBT_Project",
        live: "https://github.com/mohammedjunaidkhan980/GCP_DBT_Project",
        color: "#F2388F",
      },
      {
        id: 1,
        title: "Flight Delay Analytics Pipeline",
        description: "Real-time + batch ELT pipeline on GCP. Pub/Sub → Dataflow → GCS → PySpark → BigQuery → Looker Studio.",
        tech: ["Pub/Sub", "Dataflow", "PySpark", "BigQuery", "Airflow", "GCP"],
        image: "/images/Flight_pipeline.png",
        github: "https://github.com/mohammedjunaidkhan980/Flight_Pipeline",
        live: "https://github.com/mohammedjunaidkhan980/Flight_Pipeline",
        color: "#2F73FF",
      },
    ],
  },
  {
    id: 4,
    section: "ML & DE",
    subtitle: "// MACHINE LEARNING + DATA ENGINEERING",
    color: "#6366f1",
    projects: [
      {
        id: 6,
        title: "NLP Sentiment Analysis Pipeline",
        description: "End-to-end NLP pipeline using BERT to classify customer reviews. Pub/Sub → Dataflow → BERT → FastAPI → BigQuery → Looker Studio.",
        tech: ["BERT", "Transformers", "FastAPI", "Pub/Sub", "Dataflow", "BigQuery", "Terraform"],
        image: "/images/nlp_sentiment.png",
        github: "https://github.com/mohammedjunaidkhan980/nlp_sentiment_pipeline",
        live: "https://github.com/mohammedjunaidkhan980/nlp_sentiment_pipeline",
        color: "#6366f1",
      },
      {
        id: 7,
        title: "Real-Time Fraud Detection Pipeline",
        description: "Real-time fraud detection using TensorFlow deep learning. Transactions stream via Pub/Sub → Dataflow → FastAPI scoring → BigQuery alerts.",
        tech: ["TensorFlow", "FastAPI", "Pub/Sub", "Dataflow", "BigQuery", "Airflow", "Terraform"],
        image: "/images/fraud_detection.png",
        github: "https://github.com/mohammedjunaidkhan980/fraud_detection_pipeline",
        live: "https://github.com/mohammedjunaidkhan980/fraud_detection_pipeline",
        color: "#F2388F",
      },
    ],
  },
];

export const projects = projectSections.flatMap(s => s.projects);

export const skills = [
  { name: "Java", color: "#F2388F" },
  { name: "Spring Boot", color: "#76E36A" },
  { name: "Spring Cloud", color: "#76E36A" },
  { name: "Kafka", color: "#111111" },
  { name: "React", color: "#2F73FF" },
  { name: "Python", color: "#EFCF35" },
  { name: "GCP", color: "#2F73FF" },
  { name: "BigQuery", color: "#2F73FF" },
  { name: "dbt", color: "#F2388F" },
  { name: "PySpark", color: "#F2388F" },
  { name: "Airflow", color: "#76E36A" },
  { name: "Dataflow", color: "#2F73FF" },
  { name: "Pub/Sub", color: "#76E36A" },
  { name: "LangChain4j", color: "#111111" },
  { name: "Redis", color: "#F2388F" },
  { name: "PostgreSQL", color: "#2F73FF" },
  { name: "MongoDB", color: "#76E36A" },
  { name: "TensorFlow", color: "#FF6F00" },
  { name: "PyTorch", color: "#EE4C2C" },
  { name: "BERT", color: "#6366f1" },
  { name: "NLP", color: "#6366f1" },
  { name: "Deep Learning", color: "#F2388F" },
  { name: "FastAPI", color: "#76E36A" },
  { name: "Terraform", color: "#7B42BC" },
];

export const timeline = [
  {
    year: "Jul 2025 – Jul 2026",
    title: "Software Engineer @ Capgemini",
    description: "Joined as Java Full Stack Engineer. Built production microservices with Spring Boot and Spring Cloud.",
    color: "#2F73FF",
  },
  {
    year: "Late 2025",
    title: "Generative AI Engineering",
    description: "Built RAG HR Assistant and Multi-Agent Career Platform using LangChain4j and Azure OpenAI.",
    color: "#F2388F",
  },
  {
    year: "Early 2026",
    title: "Google Cloud Associate Engineer",
    description: "Earned Google Cloud Associate Cloud Engineer certification through Google Partner program.",
    color: "#76E36A",
  },
  {
    year: "Jul 2026 – Present",
    title: "GCP Data Engineering",
    description: "Transitioning into GCP Data Engineering. Building real-time pipelines with Pub/Sub, Dataflow, PySpark, dbt and Airflow.",
    color: "#EFCF35",
  },
];
